use super::session_manager::SessionData;
use tokio::fs;

pub async fn generate_html_report(session_id: &str, data: &SessionData) -> std::io::Result<String> {
    let dir = "public/reports";
    fs::create_dir_all(dir).await?;
    
    let file_path = format!("{}/{}.html", dir, session_id);
    let relative_path = format!("/reports/{}.html", session_id);
    
    let topics_html = data.detected_keywords
        .iter()
        .map(|k| format!("<span class='tag'>{}</span>", k))
        .collect::<Vec<_>>()
        .join("");

    let html_content = format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }}
        h1 {{ color: #0084ff; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        .field {{ margin-bottom: 20px; }}
        .label {{ font-weight: bold; color: #555; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px; }}
        .value {{ font-size: 1.2em; margin-top: 5px; }}
        .tags {{ display: flex; gap: 10px; margin-top: 5px; }}
        .tag {{ background: #e4e6eb; color: #0084ff; padding: 5px 12px; border-radius: 15px; font-weight: bold; font-size: 0.9em; }}
        .footer {{ margin-top: 50px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 20px; }}
    </style>
</head>
<body>
    <h1>Project Request Report</h1>
    <div class="field"><div class="label">Client Name</div><div class="value">{}</div></div>
    <div class="field"><div class="label">Email Address</div><div class="value">{}</div></div>
    <div class="field"><div class="label">Budget Estimate</div><div class="value">{}</div></div>
    <div class="field"><div class="label">Detected Topics</div><div class="tags">{}</div></div>
    
    <div class="footer">Generated by Rust Web Agency Assistant • Session ID: {}</div>
</body>
</html>"#,
        data.name.as_deref().unwrap_or("Unknown"),
        data.email.as_deref().unwrap_or("N/A"),
        data.budget.as_deref().unwrap_or("N/A"),
        if topics_html.is_empty() { "<span>None</span>".to_string() } else { topics_html },
        session_id
    );
    
    fs::write(&file_path, html_content).await?;
    Ok(relative_path)
}